name: dart_zeebe_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  grpc:
  protobuf: 
  fixnum:
  jwt_decoder:
  openapi:
    path: tasklist_client

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
